テストコード修正
peketo231/rspec_app_exam pull request #1
Opened 2021-02-07 11:54 UTC by peketo231

テストが成功するように修正しました。

2021-02-08 09:45 UTC, yuji91 requested changes
指摘事項についての修正は、コミットの単位を分けるようにお願いします。

2021-02-08 09:45 UTC, yuji91 commented on spec/factories/tasks.rb
> +    trait :status_done do
ステータスがdoneになって完了日が登録されることは`done`だけでも読み取れるかと思います。
```suggestion
    trait :done do
```

2021-02-08 09:45 UTC, yuji91 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
Factoryにassociationを定義するとproject_idの指定は省略できますね。
```suggestion
  let(:task) { create(:task) }
```

2021-02-08 09:45 UTC, yuji91 commented on spec/system/task_spec.rb
> +  include ApplicationHelper
設定ファイルに記載するとこのファイルだけでなく、他のSpecファイルでも該当のHelperを利用できます。

2021-02-08 09:45 UTC, yuji91 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.first)
この部分の記載は好みもありますが、1行でも記載できますね。
```suggestion
        switch_to_window(windows.last)
        expect(page).to have_content task.title
        expect(Task.count).to eq 1
        expect(current_path).to eq project_tasks_path(project)
```

2021-02-08 09:45 UTC, yuji91 commented on spec/system/task_spec.rb
> +        task = create(:task, :status_done, project_id: project.id)
let! を定義すると、変数を宣言しなくても済みますね。

2021-02-08 09:45 UTC, yuji91 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).not_to have_selector task.title
findする方針でOKです。
`have_selector`に変更した意図は特にありますか？

2021-02-09 12:52 UTC, peketo231 commented on spec/factories/tasks.rb
> +    trait :status_done do
6acbd7c で修正しました。

2021-02-09 12:55 UTC, peketo231 commented on spec/system/task_spec.rb
> +  let(:task) { create(:task, project_id: project.id) }
2468844 で修正しました。

2021-02-09 13:09 UTC, peketo231 commented on spec/system/task_spec.rb
> +  include ApplicationHelper
d50fd96 でincludeを設定ファイルに記載しました。

2021-02-09 13:09 UTC, peketo231 commented on spec/system/task_spec.rb
> +        page.driver.browser.switch_to.window(windows.first)
5c94902 で別タブ遷移コードをリファクタリングしました。

2021-02-09 14:55 UTC, peketo231 commented on spec/system/task_spec.rb
> +        expect(find('.task_list')).not_to have_selector task.title
修正漏れのため 61c5fb9 で修正しました。

2021-02-10 10:35 UTC, yuji91 requested changes
1点だけご確認をお願いします。

2021-02-10 10:35 UTC, yuji91 commented on spec/system/task_spec.rb
>          visit edit_project_task_path(project, task)
ここも変えないと`let(:task)`が呼ばれてTaskのテストデータに無駄な2件目が作成されてしまうと思います。
`binding.pry`で実行の前後の`Task.count`をご確認ください。


そもそも`let!(:task_done) { create(:task, :done) }`は「既にステータスが完了のタスクのステータスを変更した場合、Taskの完了日が更新されないこと」のテストケースの直前に定義すれば十分かもしれません。
```suggestion
        visit edit_project_task_path(project, task_done)
```

2021-02-10 14:36 UTC, peketo231 commented on spec/system/task_spec.rb
>          visit edit_project_task_path(project, task)
7568eec でTaskのテストデータが無駄に作成されないように修正しました。

2021-02-11 01:13 UTC, yuji91 approved these changes
LGTMです！

2021-02-11 08:19 UTC, merged